# Generated by Django 2.2.1 on 2019-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(default='2019-11-05 13:44:03')),
                ('complete_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
