# Generated by Django 2.2.7 on 2019-12-01 09:03

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20191120_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='todouser',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='todouser',
            name='permission',
            field=models.CharField(choices=[(todos.models.PermissionEnum('100'), '100'), (todos.models.PermissionEnum('110'), '110'), (todos.models.PermissionEnum('111'), '111')], default='100', max_length=3),
        ),
    ]
